---
title: "Third Porto"
author: "Raka R.A Prasetyo"
date: "6/20/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library("stringr")
library("dplyr")
library("readr")
library("ggplot2")
library(plyr)
library(imputeTS)
``` 

#Which game has the most profitable player in esport?

```{r}
esport <- read.csv("highest_earning_players.csv")

esport
```

```{r}
df <- esport %>% 
  dplyr::rename(
    id = PlayerId,
    f_name = NameFirst,
    l_name = NameLast,
    current_handle = CurrentHandle,
    country_code = CountryCode,
    total_usd_prize = TotalUSDPrize,
    game = Game,
    genre = Genre
  )
```

```{r}
df
```


```{r}
df_esp <- ddply(df, .(game), summarize,  total_usd_prize = mean(total_usd_prize))

df_esp
```

```{r}
ggplot(df_esp, aes(x= total_usd_prize, y= game, fill())) +
    geom_bar(stat='identity', position='dodge') + labs(y = "Game",x = "Total Prize Avg")
```


```{r}
highest_individual_score <- df %>%
  group_by(current_handle, total_usd_prize)%>%
  summarize(current_handle = current_handle, game = game, individual_score = total_usd_prize)%>%
  arrange(desc(individual_score)) %>%
  top_n(5)
```

```{r}
highest_individual_score
```

```{r}
ggplot(highest_individual_score, aes(x= current_handle, y= individual_score, fill= game)) +
    geom_bar(stat='identity', position='dodge') + labs(y = "Individual Prize",x = "Current Handle", fill = "Games")
```
